<?php

/* Translations for the datepicker external library */
return [
    'days' => [
        __('dates.long_days.7'),
        __('dates.long_days.1'),
        __('dates.long_days.2'),
        __('dates.long_days.3'),
        __('dates.long_days.4'),
        __('dates.long_days.5'),
        __('dates.long_days.6'),
    ],
    'daysShort' => [
        __('dates.short_days.7'),
        __('dates.short_days.1'),
        __('dates.short_days.2'),
        __('dates.short_days.3'),
        __('dates.short_days.4'),
        __('dates.short_days.5'),
        __('dates.short_days.6'),
    ],
    'daysMin' => [
        mb_substr(__('dates.short_days.7'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.1'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.2'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.3'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.4'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.5'), 0, 2, 'utf-8'),
        mb_substr(__('dates.short_days.6'), 0, 2, 'utf-8'),
    ],
    'months' => [
        __('dates.long_months.1'),
        __('dates.long_months.2'),
        __('dates.long_months.3'),
        __('dates.long_months.4'),
        __('dates.long_months.5'),
        __('dates.long_months.6'),
        __('dates.long_months.7'),
        __('dates.long_months.8'),
        __('dates.long_months.9'),
        __('dates.long_months.10'),
        __('dates.long_months.11'),
        __('dates.long_months.12'),
    ],
    'monthsShort' => [
        __('dates.short_months.1'),
        __('dates.short_months.2'),
        __('dates.short_months.3'),
        __('dates.short_months.4'),
        __('dates.short_months.5'),
        __('dates.short_months.6'),
        __('dates.short_months.7'),
        __('dates.short_months.8'),
        __('dates.short_months.9'),
        __('dates.short_months.10'),
        __('dates.short_months.11'),
        __('dates.short_months.12'),
    ],
    'today' => __('dates.today'),
    'clear' => __('dates.clear'),
    'dateFormat' => 'mm/dd/yyyy',
    'timeFormat' => 'hh:ii aa',
    'firstDay' => 1
];
